version: '{build}'

environment:

  matrix:
    - RUBY_VERSION: "200-x64"
      PLATFORM: "x64"
      CONDA: "true"
    - RUBY_VERSION: "200"
      PLATFORM: "Win32"
    - RUBY_VERSION: "21-x64"
      PLATFORM: "x64"
    - RUBY_VERSION: "21"
      PLATFORM: "Win32"
    - RUBY_VERSION: "22-x64"
      PLATFORM: "x64"
    - RUBY_VERSION: "22"
      PLATFORM: "Win32"
    - RUBY_VERSION: "23-x64"
      PLATFORM: "x64"
    - RUBY_VERSION: "23"
      PLATFORM: "Win32"

matrix:
  allow_failures:
    - CONDA: "true"

install:

  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - if [%PLATFORM%] == [x64] set DEVKIT=C:\Ruby23-x64\DevKit
  - if [%PLATFORM%] == [Win32] set DEVKIT=C:\Ruby23\DevKit
  - "%DEVKIT%\\devkitvars.bat"
  - gem install bundler --no-rdoc --no-ri
  - bundler env
  - bundle install
  - if not [%CONDA%] == [true] call bin/install_appveyor.cmd

build_script:
  # Build ruby gem
  - gem build symengine.gemspec
  # Install ruby gem
  - gem install symengine-0.1.0.gem --verbose
  
test_script:
  - gem install gem-path --no-ri --no-rdoc
  - gem path symengine > temp.txt
  - set /p RUBY_GEM_DIR=<temp.txt
  # Test ruby gem
  - cd %RUBY_GEM_DIR%
  - bundle exec rspec
  

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
